name: rpmlint
run-name: Lint RPM spec file
on: [push]
jobs:
  rpmlint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install rpmlint
        run: |
          sudo apt-get update
          sudo apt-get install rpmlint
      - name: Run rpmlint
        run: rpmlint xmrig.spec
